app:
  test_mode: false
  minimize_to_tray: false
twitch:
  oauth_token: ''
  broadcaster_user_id: ''
  read_all_chat: true
  reward_id: ""
tts:
  model_path: ./models/pl_zenski_1.onnx
  config_path: ./models/pl_zenski_1.onnx.json
  speaker_id: 0
  speech_rate: 1.0
  max_characters: 150
  max_queue_size: 5
  audio_device_name: Default
  padding_sec: 0.3
  volume: 1.0
filters:
  announce_username: false
  username_template: "{nick} mówi: {message}"
  enable_profanity_filter: true
  profanity_words_file: profanity_words.txt
  filter_emotes: true
  ignore_users:
    - Nightbot
    - StreamElements
    - Moobot
  max_characters: 150
  max_repeated_chars: 3
  username_aliases:
    masi4m: masiam
    utak3r: utaker
    Dr3gu: Dregu
    stream: strim
hotkeys:
  enabled: false
  mute_toggle: F9
  skip_current: F10
